apiVersion: v2
name: simple-oauth2-proxy
description: A reverse proxy  that provides authentication using providers such as Google, Microsoft etc., based on https://github.com/oauth2-proxy/oauth2-proxy
type: application
version: 0.3.7
appVersion: "7.7.0"
home: https://github.com/kostiantyn-matsebora/helm-simple-oauth2-proxy
keywords:
  - kubernetes
  - oauth
  - oauth2
  - authentication
  - google
  - github
sources:
  - https://github.com/kostiantyn-matsebora/helm-simple-oauth2-proxy
maintainers:
  - name: kostiantyn-matsebora
    email: kmatsebora@gmail.com
kubeVersion: ">=1.9.0-0"
annotations:
  artifacthub.io/alternativeName: oauth2-proxy
  artifacthub.io/category: security
  artifacthub.io/changes: |
    - Switched to quay.io/oauth2-proxy/oauth2-proxy image
  artifacthub.io/images: |
    - name: oauth2-proxy
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.0
    - name: busybox
      image: busybox:1.37.0
  artifacthub.io/license: MIT
