name: Helm

on:
  push:
    branches: [ master ]
    paths:
      - 'charts/**'
  workflow_dispatch:
      
jobs:
  publish:  
    name: Verify and publish
    runs-on: ubuntu-latest
    steps:   
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v20.0.1

      - name: List all changed tracked and untracked files
        env:
          CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
        run: |
          echo "Changed files: $CHANGED_FILES"            
      - name: Copy README.md to chart        
        run: cp README.md charts/simple-oauth2-proxy/
        if: github.ref == 'refs/heads/master'
      - name: Publish Helm chart
        if: github.ref == 'refs/heads/master'
        uses: stefanprodan/helm-gh-pages@master        
        with:
          token: ${{ secrets.HELM_BOT_GH_TOKEN }}
          charts_dir: charts
          charts_url: https://kostiantyn-matsebora.github.io/helm-charts
          owner: kostiantyn-matsebora
          repository: helm-charts
          branch: master
