name: Helm

on:
  push:
    branches: [ master ]
    paths:
      - 'charts/**'
  workflow_dispatch:
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: losisin/helm-docs-github-action@6dd725795a66c45457d6f9a7543157b9c010d77d
      - name: Generate docs
        uses: stefanprodan/helm-gh-pages@master
        with:
          chart-search-root: charts 
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.HELM_BOT_GH_TOKEN }}
          charts_dir: charts
          charts_url: https://kostiantyn-matsebora.github.io/helm-charts
          owner: kostiantyn-matsebora
          repository: helm-charts
          branch: master
