name: Helm

on:
  push:
    branches: [ master ]
    paths:
      - 'charts/**'
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]      
jobs:
  publish:  
    name: Verify and publish
    runs-on: ubuntu-latest
    steps:   
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      - name: Copy README.md to chart        
        run: cp README.md charts/simple-oauth2-proxy/
        if: github.ref == 'refs/heads/master'
      - name: Publish Helm chart
        if: github.ref == 'refs/heads/master'
        uses: stefanprodan/helm-gh-pages@master        
        with:
          token: ${{ secrets.HELM_BOT_GH_TOKEN }}
          charts_dir: charts
          charts_url: https://kostiantyn-matsebora.github.io/helm-charts
          owner: kostiantyn-matsebora
          repository: helm-charts
          branch: master
